apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-kafka-connect-operator
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  port: 9115
  liveness:
    path: "/isalive"
    initialDelay: 1
  readiness:
    path: "/isready"
    initialDelay: 1
  replicas:
    disableAutoScaling: true
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  env:
    - name: DEBUG
      value: "false"
    - name: DEBUG_UNIX_SOCKET
      value: /tmp/shell-operator/debug.socket
    - name: BASE_URL
      value: http://paw-kafka-connect:8083
  accessPolicy:
    outbound:
      rules:
        - application: paw-kafka-connect
